#!/usr/bin/env bash

bspc config border_width        1
bspc config window_gap          0
bspc config top_padding         36
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      button1
bspc config pointer_modifier    mod1
bspc config pointer_action1     move
bspc config pointer_action2     resize_corner

bspc monitor DP1 -d I II III IV V VI VII VIII IX
